"""Stable public surface for the embeddable headless core."""

from ..adapters.base import (
    AdapterHealth,
    AdapterManifest,
    MangaAdapterResult,
    MangaTranslationAdapter,
)
from ..errors import ErrorCode, LinguaError
from ..limits import ArchiveLimits
from ..providers.base import TranslationProvider, TranslationRequest, TranslationResult
from .documents import (
    build_translated_epub,
    extract_segments,
    inspect_document,
    inspect_epub,
    rebuild_document,
    translate_document,
)
from .manga import build_manga_output, extract_manga_pages, inspect_manga, translate_manga
from .models import (
    BatchStatus,
    BuildResult,
    CancellationToken,
    DocumentManifest,
    DocumentTranslationResult,
    ErrorRecord,
    EventKind,
    MangaManifest,
    MangaPage,
    MangaPageTranslation,
    MangaTranslationResult,
    Segment,
    SegmentLocator,
    SourceFormat,
    TranslationBatchResult,
    TranslationEvent,
    TranslationOptions,
    TranslationRecord,
    TranslationStatus,
)
from .orchestration import translate_segments

__all__ = [
    "AdapterHealth",
    "AdapterManifest",
    "ArchiveLimits",
    "BatchStatus",
    "BuildResult",
    "CancellationToken",
    "DocumentManifest",
    "DocumentTranslationResult",
    "ErrorCode",
    "ErrorRecord",
    "EventKind",
    "LinguaError",
    "MangaAdapterResult",
    "MangaManifest",
    "MangaPage",
    "MangaPageTranslation",
    "MangaTranslationAdapter",
    "MangaTranslationResult",
    "Segment",
    "SegmentLocator",
    "SourceFormat",
    "TranslationBatchResult",
    "TranslationEvent",
    "TranslationOptions",
    "TranslationProvider",
    "TranslationRecord",
    "TranslationRequest",
    "TranslationResult",
    "TranslationStatus",
    "build_manga_output",
    "build_translated_epub",
    "extract_segments",
    "extract_manga_pages",
    "inspect_document",
    "inspect_epub",
    "inspect_manga",
    "rebuild_document",
    "translate_document",
    "translate_manga",
    "translate_segments",
]
