"""LinguaSpindle's side-effect-free, embeddable translation core."""

from .adapters.mock_manga import MockMangaAdapter
from .core import (
    AdapterHealth,
    AdapterManifest,
    ArchiveLimits,
    BatchStatus,
    BuildResult,
    CancellationToken,
    DocumentManifest,
    DocumentTranslationResult,
    ErrorCode,
    ErrorRecord,
    EventKind,
    LinguaError,
    MangaAdapterResult,
    MangaManifest,
    MangaPage,
    MangaPageTranslation,
    MangaTranslationAdapter,
    MangaTranslationResult,
    Segment,
    SegmentLocator,
    SourceFormat,
    TranslationBatchResult,
    TranslationEvent,
    TranslationOptions,
    TranslationProvider,
    TranslationRecord,
    TranslationRequest,
    TranslationResult,
    TranslationStatus,
    build_manga_output,
    build_translated_epub,
    extract_manga_pages,
    extract_segments,
    inspect_document,
    inspect_epub,
    inspect_manga,
    rebuild_document,
    translate_document,
    translate_manga,
    translate_segments,
)
from .providers.mock import MockProvider

__version__ = "0.3.0"

__all__ = [
    "AdapterHealth",
    "AdapterManifest",
    "ArchiveLimits",
    "BatchStatus",
    "BuildResult",
    "CancellationToken",
    "DocumentManifest",
    "DocumentTranslationResult",
    "ErrorCode",
    "ErrorRecord",
    "EventKind",
    "LinguaError",
    "MangaAdapterResult",
    "MangaManifest",
    "MangaPage",
    "MangaPageTranslation",
    "MangaTranslationAdapter",
    "MangaTranslationResult",
    "MockMangaAdapter",
    "MockProvider",
    "Segment",
    "SegmentLocator",
    "SourceFormat",
    "TranslationBatchResult",
    "TranslationEvent",
    "TranslationOptions",
    "TranslationProvider",
    "TranslationRecord",
    "TranslationRequest",
    "TranslationResult",
    "TranslationStatus",
    "build_manga_output",
    "build_translated_epub",
    "extract_segments",
    "extract_manga_pages",
    "inspect_document",
    "inspect_epub",
    "inspect_manga",
    "rebuild_document",
    "translate_document",
    "translate_manga",
    "translate_segments",
]
